version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        SHARED_WORKSPACE_HOST: ${SHARED_WORKSPACE_HOST}
        SHARED_WORKSPACE_CONTAINER: ${SHARED_WORKSPACE_CONTAINER}
        NODE_VERSION: ${NODE_VERSION}
    image: reactapp_dev
    container_name: reactapp_dev
    ports:
      # 開発でのローカルサーバ起動用
      - 8760:8760
      # webpack-bundle-analyzer用
      - 8765:8765
    volumes:
      - ./${SHARED_WORKSPACE_HOST}:${SHARED_WORKSPACE_CONTAINER}
      # ---------------------------------------------------------------------------
      # コンテナ側のnode_modulesディレクトリをホスト側に持ってこないようにする．
      # https://stackoverflow.com/a/37898591
      # なんかディレクトリ作られるけど，中身はホストへ共有されてない．まぁいいか…？
      # でもこれをすると，ホスト側の開発でエラーの赤波線が出てしまう…
      # - ${SHARED_WORKSPACE_CONTAINER}/frontend/node_modules/
      # - ${SHARED_WORKSPACE_CONTAINER}/backend/node_modules/
      # ---------------------------------------------------------------------------
      # 下記は緊急編集用．
      - ./docker/dev/tools:/opt/docker/tools
      # ---------------------------------------------------------------------------
    tty: true

  # app@preview:
  # 	build:
  # 		context: .
  # 		dockerfile: ./docker/preview/app/Dockerfile
  # 		args:
  # 	image: reactapp_prev
  # 	container_name: reactapp_prev
  # 	volumes:
  # 		- ./${SHARED_WORKSPACE_HOST}/webpack_build/dist:/var/www/reactapp
  # 	ports:
  # 		- 
    
  # db@preview:
  # phpmyadmin@preview

